# Docker compose to build and run the config service
version: '3'
services:
  atto-config-server.common.svc:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8888:8080"

networks:
  default:
    external:
      name: springboot