# Docker compose to build and run the eureka service
version: '3'
services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8888:8080"

networks:
  default:
    external:
      name: springboot